////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Algorithms.Data
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class Employee
//    {
//        public int EmployeeID { get; set; }
//        public string EmployeeName { get; set; }
//        public string EmployeeEmail { get; set; }
//        public string EmployeeContactNo { get; set; }
//        public int EmployeeDepartmentId { get; set; }
//        public string EmployeeAddress { get; set; }
    
//        public virtual Department Department { get; set; }
//    }
//}
